### ISSUE TITLE
Map to PNG: colour palette

### ISSUE THREAD

**Issue by im-dima** [zenenwjaimes/nbt-tools#12]
Hello Zenen 👋 

First of all, thanks a lot for this awesome tool: https://blocky.tools/maps, it works like a charm and really serves its purpose! The only downside is the outdated color palette. For instance, _Deepslate_ and _Copper_ are rendered in dark-red colour instead of their real in-game colours. I guess the colour palette was not updated since you released the tool and back those days we didn't have these materials/blocks in **Minecraft**. It would be awesome if you could update the colour palette to include latest materials/blocks.

Thanks in advance!

**Comment by zenenwjaimes** [comment]
Hey! I’m glad that you like the tool. You’re definitely right, I haven’t updated the color palettes since about 1.16. I’m going to take a look at this, thank you for bringing it to my attention.

**Comment by zenenwjaimes** [comment]
I've fixed this issue, please let me know if you see any other issues. Thanks again for using the app!
